austin_bikeshare_demo:
  outputs:
    dev:
      dataset: austin_bikeshare_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: spry-pier-478012-a2
      threads: 1
      type: bigquery
  target: dev
liquor_sales:
  outputs:
    dev:
      dataset: austin_bikeshare_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: spry-pier-478012-a2
      threads: 1
      type: bigquery
  target: dev
